drop table if exists bookmarks;

create table bookmarks (
    id INTEGER primary key generated by default as identity,
    title text,
    url text,
    description TEXT,
    rating INTEGER,
);

INSERT INTO bookmarks (title, url, description, rating)
 VALUES (
     ( 'Thinkful', 'https://www.thinkful.com', 'Think outside the classroom', '5'),
     ( 'Google', 'https://www.google.com', 'Where we find everything else',
     '4'),
     ( 'MDN', 'https://developer.mozilla.org/en-US', 'The only place to find web documents', '5');
     
 )